### ISSUE TITLE
Node 8 is EOL

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#122]
Node 8 is end-of-life and should be upgraded

https://github.com/LCAS/pgr_system/blob/19dda2a8295ef31c030c49a3bd15143bb4e1a6ee/Dockerfile#L17

https://github.com/LCAS/pgr_system/blob/19dda2a8295ef31c030c49a3bd15143bb4e1a6ee/Dockerfile.devel#L12

It may also be worth separating the frontend build phase into its own node based container that can exit once all the assets are built

**Comment by marc-hanheide** [comment]
> It may also be worth separating the frontend build phase into its own node based container that can exit once all the assets are built

Never done that... do you know how that works? And what benefit it would offer?

**Comment by pet1330** [comment]
It just seperates out the javascript from your PHP code. The less code you have in your production container the better.


You can just remove the node commands from your Dockerfile and then in your docker-compose file you add:
```
  frontend:
    image: node
    depends_on:
      - [YOUR_BACKEND_CONTAINER]
    volumes:
      - /var/www/pgr/public:/var/www/pgr/public
      - /var/www/pgr/resources:/var/www/pgr/resouces
     - /var/www/pgr/package.json:/var/www/pgr/package.json
    - etc, etc...
    working_dir: /var/www/pgr
    command: "bash -c 'yarn --ignore-engines && yarn run production'"
```
When you run `docker-composer up`, it starts this container, it downloads your dependancies, compiles your frontend using webpack then exits.

You probably want to keep your node_modules folder for development, so in the docker-compose-devel files, you can have something like:

```
  frontend:
    image: node
    depends_on:
      - [YOUR_BACKEND_CONTAINER]
    volumes:
      - /var/www/pgr:/var/www/pgr
    working_dir: /var/www/pgr
    command: "bash -c 'yarn --ignore-engines && yarn run watch'"
```
Which will watch for file changes in the background and recompile when edits are made.
